### ISSUE TITLE
Spring Sale 2023 error

### ISSUE THREAD

**Issue by MonolithOrchids** [quer/the-steam-awards#64]
```
[34m [Thu, 16 Mar 2023 20:21:13 GMT][00 - account] [36m     at module.exports.<anonymous> (xxx\the-steam-awards-2.0.0\lib\CoreSteam.js:98:18) [0m account

[34m [Thu, 16 Mar 2023 20:21:13 GMT][00 - account] [36m     at module.exports.<anonymous> (xxx\the-steam-awards-2.0.0\lib\CoreSteam.js:104:22) [0m Connected to Steam.

[34m [Thu, 16 Mar 2023 20:21:32 GMT][00 - xxxx - account] [36m     at module.exports.<anonymous> (xxx\the-steam-awards-2.0.0\lib\CoreSteam.js:202:18) [0m websession start

[44m [34m 🚩[Thu, 16 Mar 2023 20:21:34 GMT][00 - xxxx - account][FreeDailySticker] 
[36m     at module.exports (xxx\the-steam-awards-2.0.0\modules\events\FreeDailySticker.js:13:9) [0m failed to get authwgtoken, will try agirn

[44m [34m 🚩[Thu, 16 Mar 2023 20:21:34 GMT][00 - xxxx - account][FreeDailySticker] [36m     at module.exports (xxx\the-steam-awards-2.0.0\modules\events\FreeDailySticker.js:21:9) [0m error no authwgtoken

[34m [Thu, 16 Mar 2023 20:21:34 GMT][00 - xxxx - account][FreeDailySticker] [36m     at module.exports.onSteamLogOn (xxx\the-steam-awards-2.0.0\lib\CoreSteam.js:161:30) [0m Account Done!

[34m [Thu, 16 Mar 2023 20:21:34 GMT][00 - xxxx - account] [36m     at module.exports.onSteamLogOn (xxx\the-steam-awards-2.0.0\lib\CoreSteam.js:177:22) [0m Account disconnect
```

**Comment by quer** [comment]
hey, can i get you to validate that the account can se/use the point shop?
as it is getting the `authwgtoken` from there. 

so just open `https://store.steampowered.com/points/shop` ( the point shop ) 
And paste this into the DevTool ( F12 )
`JSON.parse(jQuery("#application_config").attr("data-loyaltystore")).webapi_token`
It will print the key. if you are able to see a key, here. then there might be somefing wrong whit the module. 
If you doent see the key, then you account is not activ Or valid to get the free sticket. 

can i get you to validate the above ?

**Comment by MonolithOrchids** [comment]
Hey,
Yeah it does validate with a key, account has over 10k games.

**Comment by quer** [comment]
Okay, then it shoud be all right.

did you only run it once or did you try multiple times? 

what i need you to test, is logging what steam send as the container of the token

in file and line :
https://github.com/quer/the-steam-awards/blob/Master/modules/events/FreeDailySticker.js#L38
add the following under.
```js
log(authwgtoken)
```
( so it look like this : )
```js
var authwgtoken = JSON.parse($("#application_config").attr("data-loyaltystore"));
log(authwgtoken)
resolve(authwgtoken);
```


Then run it agirn. and it shoud print the same, that you did see in the devtool. Then you can see if the `webapi_token` is set in both places.

**Comment by MonolithOrchids** [comment]
I tried multiple times on multiple accounts, accounts using 2FA and accounts using Email Login, all accounts that aren't limited.

I did what you said and got the same result.

**Comment by quer** [comment]
Then in basic, it shoud work. You have to send me the `authwgtoken` that is printet. for me to be able to help more.
