### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined

### ISSUE THREAD

**Issue by mrranger** [quer/the-steam-awards#75]
Don't pay attention to the-steam-awards-2.0.0, in fact this is the latest version that I just downloaded

 [Tue, 21 Nov 2023 18:50:34 GMT][MYNAMEACC]      at module.exports.<anonymous> (D:\SteamEventStart\the-steam-awards-2.0.0\lib\CoreSteam.js:98:18)  MYNAMEACC
 [Tue, 21 Nov 2023 18:50:34 GMT][MYNAMEACC]      at module.exports.<anonymous> (D:\SteamEventStart\the-steam-awards-2.0.0\lib\CoreSteam.js:104:22)  Connected to Steam.
 [Tue, 21 Nov 2023 18:50:49 GMT][id - MYNAMEACC]      at module.exports.<anonymous> (D:\SteamEventStart\the-steam-awards-2.0.0\lib\CoreSteam.js:202:18)  websession start
node:internal/errors:496
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined
    at new NodeError (node:internal/errors:405:5)
    at Function.from (node:buffer:333:9)
    at new Buffer (node:buffer:288:17)
    at SteamWebLogOn.webLogOn (D:\SteamEventStart\the-steam-awards-2.0.0\node_modules\steam-weblogon\index.js:28:7)
    at module.exports.<anonymous> (D:\SteamEventStart\the-steam-awards-2.0.0\lib\CoreSteam.js:203:27)
    at new Promise (<anonymous>)
    at module.exports.websession (D:\SteamEventStart\the-steam-awards-2.0.0\lib\CoreSteam.js:201:16)
    at module.exports.onSteamLogOn (D:\SteamEventStart\the-steam-awards-2.0.0\lib\CoreSteam.js:131:97)
    at SteamClient.emit (node:events:526:35)
    at handlers.<computed> (D:\SteamEventStart\the-steam-awards-2.0.0\node_modules\steam\lib\steam_client.js:281:8) {
  code: 'ERR_INVALID_ARG_TYPE'
}

Node.js v18.17.1

**Comment by quer** [comment]
i am create a new module for this event.

**Comment by mrranger** [comment]
> i am create a new module for this event.

It’s just that I kind of tried to check any event, or the same nomination, every time I get an error, if this is not my problem then okay, I apologize for the trouble, I’ll wait for the update!

**Comment by quer** [comment]
Hey, just had a more deeper read on the problem you have. i saw it as a module that fails. But it is the script. 

You have to get the newest version of the code,, as it doent use the `steam-weblogon` module any more. 

you can read more on it, in the top of the `readme.md` ( front page, in this project. )

it was changed here 
https://github.com/quer/the-steam-awards/commit/65891645638bdb69529a016b3dc39ac36662f748  
on Oct 26, 2023
