### ISSUE TITLE
New version doesn't work

### ISSUE THREAD

**Issue by Magellano** [quer/the-steam-awards#76]
Hi.
I updated to the latest version, but now it doesn't work at all.
After running node main I get a message that the module was not found. Below I provide the error code. Or maybe I'm doing something wrong?

```
:/home/clouds/node/the-steam-awards-Master$ node main
internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module './lib/Core'
Require stack:
- /home/clouds/node/the-steam-awards-Master/main.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/clouds/node/the-steam-awards-Master/main.js:2:14)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/clouds/node/the-steam-awards-Master/main.js' ]
}

```

**Comment by quer** [comment]
in the main.js file.
if you change the upper C to a small c, in the core word. 
As i can see that the file it refere to, is speld whit a small c

Then do it work.?

as i can see there is a Uppercase there in there. Maby your system. is case sensitive. I did not take into consideration, that it choud be a problem. I will fix all the places, that you find.

**Comment by Magellano** [comment]
> in the main.js file. if you change the upper C to a small c, in the core word. As i can see that the file it refere to, is speld whit a small c
> 
> Then do it work.?
> 
> as i can see there is a Uppercase there in there. Maby your system. is case sensitive. I did not take into consideration, that it choud be a problem. I will fix all the places, that you find.


I corrected the letter to lower case, now it looks like this:

```c
Error: Cannot find module 'steam-totp'
Require stack:
- /home/clouds/node/the-steam-awards-Master/lib/CoreSteam.js
- /home/clouds/node/the-steam-awards-Master/lib/core.js
- /home/clouds/node/the-steam-awards-Master/main.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/clouds/node/the-steam-awards-Master/lib/CoreSteam.js:1:19)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/clouds/node/the-steam-awards-Master/lib/CoreSteam.js',
    '/home/clouds/node/the-steam-awards-Master/lib/core.js',
    '/home/clouds/node/the-steam-awards-Master/main.js'
  ]
}
```

**Comment by quer** [comment]
have you done "npm i" when you, upgrade you script to the new one? 

if yes, then in the "node_modules" folder, can you see the "steam-totp" folder ? can se see the name of the folder match the text, from the top of CoreSteam.js file ?

**Comment by quer** [comment]
as it saying that you did not install that module.

**Comment by Magellano** [comment]
> as it saying that you did not install that module.

indeed, the first time I forgot to run the command "npm i"
The second time I reinstalled completely, ran the update, corrected the letter as you recommended. Now I have the following


```c
/home/clouds/node/the-steam-awards-Master$ node main
/home/clouds/node/the-steam-awards-Master/node_modules/steam-user/components/03-messages.js:740
                                machineId: this._logOnDetails?.machine_id
                                                              ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/clouds/node/the-steam-awards-Master/node_modules/steam-user/components/content_manifest.js:4:27)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
```

**Comment by quer** [comment]
you nodejs, might to old. As the logic whit "?." was added in version
14
`Optional chaining is currently not supported in Node.js version 13 and below`
https://stackoverflow.com/questions/59574047/how-to-use-optional-chaining-in-node-js-12

**Comment by Magellano** [comment]
> you nodejs, might to old. As the logic whit "?." was added in version 14 `Optional chaining is currently not supported in Node.js version 13 and below` https://stackoverflow.com/questions/59574047/how-to-use-optional-chaining-in-node-js-12

Indeed, I had version 12 from the Debian repository. After installing the new version, almost everything worked. Except for publishing a review. Here the script throws an error. Could this be because there is already a review for this game (440)?

```c
at module.exports.<anonymous> (/home/clouds/node/the-steam-awards-Master/lib/CoreSteam.js:100:22)  Logged into Steam as [U:1:********]
 [Wed, 22 Nov 2023 18:12:30 GMT][765611*********** - myaccount]      at module.exports.<anonymous> (/home/clouds/node/the-steam-awards-Master/lib/CoreSteam.js:108:22)  Got web session
 [Wed, 22 Nov 2023 18:12:30 GMT][765611*********** - myaccount]      at module.exports.websession (/home/clouds/node/the-steam-awards-Master/lib/CoreSteam.js:154:14)  websession start
 [Wed, 22 Nov 2023 18:12:37 GMT][765611*********** - myaccount][steamawards-2023]      at /home/clouds/node/the-steam-awards-Master/modules/events/steamawards-2023.js:151:33  was not able to create recommendgame, error: There was a problem posting your review.
 [Wed, 22 Nov 2023 18:12:39 GMT][765611*********** - myaccount][steamawards-2023]      at /home/clouds/node/the-steam-awards-Master/modules/events/steamawards-2023.js:151:33  was not able to create recommendgame, error: There was a problem posting your review.
 [Wed, 22 Nov 2023 18:12:40 GMT][765611*********** - myaccount][steamawards-2023]      at /home/clouds/node/the-steam-awards-Master/modules/events/steamawards-2023.js:151:33  was not able to create recommendgame, error: There was a problem posting your review.
 [Wed, 22 Nov 2023 18:12:41 GMT][765611*********** - myaccount][steamawards-2023]      at /home/clouds/node/the-steam-awards-Master/modules/events/steamawards-2023.js:151:33  was not able to create recommendgame, error: There was a problem posting your review.
 [Wed, 22 Nov 2023 18:12:42 GMT][765611*********** - myaccount][steamawards-2023]      at /home/clouds/node/the-steam-awards-Master/modules/events/steamawards-2023.js:151:33  was not able to create recommendgame, error: There was a problem posting your review.
 [Wed, 22 Nov 2023 18:12:43 GMT][765611*********** - myaccount][steamawards-2023]      at /home/clouds/node/the-steam-awards-Master/modules/events/steamawards-2023.js:151:33  was not able to create recommendgame, error: There was a problem posting your review.
 [Wed, 22 Nov 2023 18:12:44 GMT][765611*********** - myaccount][steamawards-2023]      at /home/clouds/node/the-steam-awards-Master/modules/events/steamawards-2023.js:151:33  was not able to create recommendgame, error: There was a problem posting your review.
 [Wed, 22 Nov 2023 18:12:44 GMT][765611*********** - myaccount][steamawards-2023]      at /home/clouds/node/the-steam-awards-Master/modules/events/steamawards-2023.js:106:37  1 task done, out of 4
 [Wed, 22 Nov 2023 18:12:44 GMT][765611*********** - myaccount][steamawards-2023]      at /home/clouds/node/the-steam-awards-Master/modules/events/steamawards-2023.js:107:37  tasks: (1:done) (2:done) (3:done) (4:not done)
 [Wed, 22 Nov 2023 18:12:44 GMT][765611*********** - myaccount][steamawards-2023]      at module.exports.<anonymous> (/home/clouds/node/the-steam-awards-Master/lib/CoreSteam.js:137:26)  Account Done!
```

**Comment by quer** [comment]
The problem her, can be that your account, is locked from doing reviews, of games. 
can i get you to test, one of the account, if you can manuel do a review for Team fortress, on one of the account that do say that. 

as that error means that, steam did not allow you to do a review on that game. 

you can see that it did do 3 out of 4 thinks ( `tasks: (1:done) (2:done) (3:done) (4:not done)` ) 
did just see a small error in the script. it do turn the message, the wrong way around. 
the `1 task done, out of 4` meas that it is `missing 1 out of 4`.

**Comment by Magellano** [comment]
> The problem her, can be that your account, is locked from doing reviews, of games. can i get you to test, one of the account, if you can manuel do a review for Team fortress, on one of the account that do say that.
> 
> as that error means that, steam did not allow you to do a review on that game.

No, accounts are not blocked from posting reviews.

I checked. The script does not perform this task if there is already a review for the game. If I delete the review, then the script is processed successfully.

As far as I remember, in the previous version the script worked even if the account had a game review

**Comment by quer** [comment]
okay, thanks, i will just add, so it trys to delete one, if exist, before making the review.

**Comment by quer** [comment]
if yuo still have account that have the problem. Can i get you to test it. as where i am, i am not able to test the code. 

But in https://github.com/quer/the-steam-awards/blob/Master/modules/events/steamawards-2023.js#L46C17-L46C60 where the `await Make(steamClient.steamID, appToPlay);` is. Add the following, just above that code. As then it will just remove it, before making the review


```js
await new Promise(function (resolve) {
    removeMake(steamClient.steamID, appToPlay, resolve)
});
```

**Comment by Magellano** [comment]
If I added the code correctly, it now looks like this.
```javascript
        steamClient.gamesPlayed([]);
        var reviewLoopTimes = 0;
        while (reviewLoopTimes < 7) {
            var status = await EnsureWeAreDone();
            if(!status.list[3].completed){
				await new Promise(function (resolve) {
    removeMake(steamClient.steamID, appToPlay, resolve)
			});
                await Make(steamClient.steamID, appToPlay);
                ++reviewLoopTimes;
            }else{
                break;
            }
        }
``` 

Now the script deletes the review if it was previously present, but does not add a new review. The script just sits idle at this stage
```javascript
/home/clouds/node/the-steam-awards-Master$ node main
 [Thu, 23 Nov 2023 10:00:58 GMT][myaccount]      at module.exports.<anonymous> (/home/clouds/node/the-steam-awards-Master/lib/CoreSteam.js:100:22)  Logged into Steam as [U:1:954******]
 [Thu, 23 Nov 2023 10:01:00 GMT][76561************ - myaccount]      at module.exports.<anonymous> (/home/clouds/node/the-steam-awards-Master/lib/CoreSteam.js:108:22)  Got web session
 [Thu, 23 Nov 2023 10:01:00 GMT][76561************ - myaccount]      at module.exports.websession (/home/clouds/node/the-steam-awards-Master/lib/CoreSteam.js:154:14)  websession start
 [Thu, 23 Nov 2023 10:01:06 GMT][76561************ - myaccount][steamawards-2023]      at /home/clouds/node/the-steam-awards-Master/modules/events/steamawards-2023.js:179:25  fjerenet

```

**Comment by quer** [comment]
oh, you are right!

you did it right. Just add this insted of what you did before

`await removeMake(steamClient.steamID, appToPlay);`

so: 
```
 if(!status.list[3].completed){
		await removeMake(steamClient.steamID, appToPlay);
                await Make(steamClient.steamID, appToPlay);
                ++reviewLoopTimes;

```

**Comment by Magellano** [comment]
It seems to be working now. Hurray!
I tested this on a group of accounts. Where there was already a review, the script deletes it, then publishes it again and deletes it again.

Thank you for your help. You are cool =^_^=

**Comment by quer** [comment]
Perfekt!

thank for using it :)
