### ISSUE TITLE
machineId: this._logOnDetails?.machine_id

### ISSUE THREAD

**Issue by stickerx** [quer/the-steam-awards#78]

**Comment by stickerx** [comment]
the-steam-awards-Master\node_modules\steam-user\components\03-messages.js:740
                                machineId: this._logOnDetails?.machine_id
                                                              ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (C:\Users\Meneow\Desktop\the-steam-awards-Master\node_modules\steam-user\components\content_manifest.js:4:27)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10) (C:\Users\Meneow\Desktop\the-steam-awards-Master\node_modules\steam-user\components\content_manifest.js:4:27)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)

**Comment by quer** [comment]
you need to update your nodejs. 

read more in this issue comment 
https://github.com/quer/the-steam-awards/issues/76#issuecomment-1822802093

**Comment by quer** [comment]
i will just make that line, in the old way. so there might not be a reason to upgrade.
